# Use the lightweight Nginx image
FROM nginx:alpine

# Copy the specific HTML file to the Nginx web directory
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80 for the container
EXPOSE 80